### ISSUE TITLE
Broken for MacOS (Apple silicone)

### ISSUE THREAD

**Issue by Floorpancake** [ari-party/mtc-artillery#256]
Opening the downloaded app (aarch64.dmg) returns error: 
“mtc-artillery-overlay” is damaged and can’t be opened. You should eject the disk image.
or 
“mtc-artillery-overlay” is damaged and can’t be opened. You should move it to the Trash. 
if moved to applications

**Comment by ari-party** [comment]
There are 2 images for Apple, `aarch64` and `x64`. Have you tried the other one?

**Comment by Floorpancake** [comment]
Tried both, using apple silicone M1Pro MBP.

**Comment by ari-party** [comment]
Try the following:
Open the terminal/console
Run `xattr -c "path to mtc-artillery-overlay app"`

**Comment by ari-party** [comment]
I'm dropping support for MacOS. You can compile it yourself if you want, it's not in my interest to maintain it for either.
