### ISSUE TITLE
libwebkit2gtk-4.0-37 not available on Linux Mint 22, cant install

### ISSUE THREAD

**Issue by ghost** [ari-party/mtc-artillery#257]
![image](https://github.com/user-attachments/assets/f031e855-5b7a-438f-84f7-8bd73198c296)
![image](https://github.com/user-attachments/assets/1dba749a-0191-4469-a2d4-0ac5c971878d)

**Comment by ari-party** [comment]
`webkit2gtk-4.0` has been made legacy and is part of Tauri v1. Debian installations for `mtc-artillery-overlay` will be unavailable until I migrated to Tauri v2 (which uses webkit2gtk-4.1+)

Closing this issue once I migrated to v2.

**Comment by ari-party** [comment]
Fixed with [v0.2.7](https://github.com/grand-hawk/artillery-calculator/releases/tag/overlay-v0.2.7)
Video: https://www.youtube.com/watch?v=eBrLdnb1EVA
