### ISSUE TITLE
Newest version virus issue

### ISSUE THREAD

**Issue by Jasii-S** [ari-party/mtc-artillery#50]
No idea if this is known or to be expected, but windows defender sees this as a trojan and deletes it automatically.
Virustotal also really does not like it.
https://www.virustotal.com/gui/file/ecd2ee86abc3d54ed051a2abfe3b4d4188578554c004ff253114366e80bc0c49

I apologize if this is known already or to be expected, its 2am and I am tired as hell.

**Comment by ari-party** [comment]
https://github.com/tauri-apps/tauri/issues/2486

can't fix :(
